### PR TITLE
(SIMP-4654) Test against latest GDM

### PR DESCRIPTION
**Pull request by trevor-vaughan**
* Updated the tests to work against the latest GDM
* Removed the section that enabled XDMCP explicitly since this has
  security implications that the admin should really opt-into
  specifically via the GDM module

### CODE REVIEW

**Comment by jeefberkey** [comment]
https://gitlab.com/simp/pupmod-simp-vnc/pipelines/24531000

**Comment by jeefberkey** [comment]
There needs to be a release before this is merged

**Comment by lnemsick-simp** [comment]
https://gitlab.com/simp/pupmod-simp-vnc/pipelines/24777240

**Comment by lnemsick-simp** [comment]
https://gitlab.com/simp/pupmod-simp-vnc/pipelines/24778518

**Pull request merged**
